/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buyer;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Sanjana
 */
public class ownerform extends javax.swing.JFrame {

    /**
     * Creates new form ownerform
     */
    public ownerform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlevar = new javax.swing.JLabel();
        vname = new javax.swing.JLabel();
        vphone = new javax.swing.JLabel();
        areatxt = new javax.swing.JTextField();
        vaddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addrtxt = new javax.swing.JTextArea();
        vbhk = new javax.swing.JLabel();
        varea = new javax.swing.JLabel();
        bhktxt = new javax.swing.JTextField();
        vrent = new javax.swing.JLabel();
        renttxt = new javax.swing.JTextField();
        submitbut = new javax.swing.JButton();
        displaytxt = new javax.swing.JLabel();
        clearbut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        yesfur = new javax.swing.JRadioButton();
        nofur = new javax.swing.JRadioButton();
        yespar = new javax.swing.JRadioButton();
        nopar = new javax.swing.JRadioButton();
        locn = new javax.swing.JLabel();
        locntxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formpg");

        titlevar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titlevar.setText("Owner Form");

        vname.setText("Furnished");

        vphone.setText("Parking");

        areatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areatxtActionPerformed(evt);
            }
        });

        addrtxt.setColumns(20);
        addrtxt.setRows(5);
        jScrollPane1.setViewportView(addrtxt);

        vbhk.setText("BHK");

        varea.setText("Area(sqft)");

        bhktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhktxtActionPerformed(evt);
            }
        });

        vrent.setText("Rent");

        renttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renttxtActionPerformed(evt);
            }
        });

        submitbut.setText("Submit");
        submitbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbutActionPerformed(evt);
            }
        });

        displaytxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        clearbut.setText("Clear");
        clearbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbutActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("<-Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Property Address");

        yesfur.setText("yes");
        yesfur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesfurActionPerformed(evt);
            }
        });

        nofur.setText("no");
        nofur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nofurActionPerformed(evt);
            }
        });

        yespar.setText("yes");
        yespar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesparActionPerformed(evt);
            }
        });

        nopar.setText("no");
        nopar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noparActionPerformed(evt);
            }
        });

        locn.setText("Location");

        locntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locntxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vphone)
                                .addComponent(vaddress)
                                .addComponent(vbhk)
                                .addComponent(varea)
                                .addComponent(vrent)
                                .addComponent(jLabel1)
                                .addComponent(vname))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(207, 207, 207)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(areatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(bhktxt, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addComponent(renttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addComponent(locntxt, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(195, 195, 195)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(yespar)
                                        .addComponent(yesfur))
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nofur)
                                        .addComponent(nopar)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(displaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titlevar)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(submitbut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                    .addComponent(clearbut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlevar)
                    .addComponent(jButton1))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesfur)
                    .addComponent(nofur)
                    .addComponent(vname))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vphone)
                    .addComponent(yespar)
                    .addComponent(nopar))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(vaddress)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locn)
                    .addComponent(locntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varea, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vbhk)
                    .addComponent(bhktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vrent)
                    .addComponent(renttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitbut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displaytxt)
                    .addComponent(clearbut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areatxtActionPerformed

    private void bhktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bhktxtActionPerformed

    private void renttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renttxtActionPerformed

    private void submitbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbutActionPerformed
        // TODO add your handling code here:
        //String name = nmtxt.getText();
        //System.out.println(name);
        //String phone = phonetxt.getText();
        
        String addr = addrtxt.getText();
        String area = areatxt.getText();
        String bhk = bhktxt.getText();
        String rent = renttxt.getText();
        String locnn = locntxt.getText();
        String fur = "";
        
        if(yesfur.isSelected())
        {
            fur = "Yes";
        }
        else{
            fur="No";
        }
        String par;
        if(yespar.isSelected())
        {
            par = "Yes";
        }
        else{
            par="No";
        }
        if(addr.length()!=0 && area.length()!=0 && bhk.length()!=0 && rent.length()!=0 && locnn.length()!=0){
            displaytxt.setText("Submitted succesfully");
             try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/realestate","root","yashaswini22")){
                String sql="insert into rent_owner values(\""+LoginF.em+"\","+area+","+bhk+",\""+locnn+"\","+rent+",\""+fur+"\",\""+par+"\",\""+addr+"\")";
                PreparedStatement pstmt=conn.prepareStatement(sql);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"insertion successfull");
                conn.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            } 
           

        }
        else{
            displaytxt.setText("Form incomplete");
            //System.out.println(phone.length());
        }
        
        
    }//GEN-LAST:event_submitbutActionPerformed

    private void clearbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbutActionPerformed
        // TODO add your handling code here:
        //nmtxt.setText("");
        //phonetxt.setText("");
        addrtxt.setText("");
        areatxt.setText("");
        locntxt.setText("");
        bhktxt.setText("");
        renttxt.setText("");
    }//GEN-LAST:event_clearbutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RentalServicesPage bo = new RentalServicesPage();
        bo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yesfurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesfurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesfurActionPerformed

    private void nofurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nofurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nofurActionPerformed

    private void noparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noparActionPerformed

    private void yesparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesparActionPerformed

    private void locntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locntxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addrtxt;
    private javax.swing.JTextField areatxt;
    private javax.swing.JTextField bhktxt;
    private javax.swing.JButton clearbut;
    private javax.swing.JLabel displaytxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locn;
    private javax.swing.JTextField locntxt;
    private javax.swing.JRadioButton nofur;
    private javax.swing.JRadioButton nopar;
    private javax.swing.JTextField renttxt;
    private javax.swing.JButton submitbut;
    private javax.swing.JLabel titlevar;
    private javax.swing.JLabel vaddress;
    private javax.swing.JLabel varea;
    private javax.swing.JLabel vbhk;
    private javax.swing.JLabel vname;
    private javax.swing.JLabel vphone;
    private javax.swing.JLabel vrent;
    private javax.swing.JRadioButton yesfur;
    private javax.swing.JRadioButton yespar;
    // End of variables declaration//GEN-END:variables
}
