/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buyer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author yashaswini nagarajan
 */
public class sellerform extends javax.swing.JFrame {

    /**
     * Creates new form sellerform
     */
    public sellerform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        isloc = new javax.swing.JTextField();
        vsqft = new javax.swing.JLabel();
        vsloc = new javax.swing.JLabel();
        isqft = new javax.swing.JTextField();
        vspar = new javax.swing.JLabel();
        isprice = new javax.swing.JTextField();
        vsprice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isaddr = new javax.swing.JTextArea();
        vsaddr = new javax.swing.JLabel();
        vsfur = new javax.swing.JLabel();
        yesfur = new javax.swing.JRadioButton();
        nospar = new javax.swing.JRadioButton();
        displayselltxt = new javax.swing.JLabel();
        nofur = new javax.swing.JRadioButton();
        yespar = new javax.swing.JRadioButton();
        ssub = new javax.swing.JButton();
        sclr = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        isbhk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel1.setText("Seller Commercial Form");

        isloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islocActionPerformed(evt);
            }
        });

        vsqft.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vsqft.setText("Square Feet");

        vsloc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vsloc.setText("Location");

        isqft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isqftActionPerformed(evt);
            }
        });

        vspar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vspar.setText("Parking");

        isprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ispriceActionPerformed(evt);
            }
        });

        vsprice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vsprice.setText("Price");

        isaddr.setColumns(20);
        isaddr.setRows(5);
        jScrollPane1.setViewportView(isaddr);

        vsaddr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vsaddr.setText("Address");

        vsfur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vsfur.setText("Furnished");

        buttonGroup1.add(yesfur);
        yesfur.setText("Yes");
        yesfur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesfurActionPerformed(evt);
            }
        });

        buttonGroup2.add(nospar);
        nospar.setText("No");

        buttonGroup1.add(nofur);
        nofur.setText("No");
        nofur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nofurActionPerformed(evt);
            }
        });

        buttonGroup2.add(yespar);
        yespar.setText("Yes");
        yespar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesparActionPerformed(evt);
            }
        });

        ssub.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ssub.setText("Submit");
        ssub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssubActionPerformed(evt);
            }
        });

        sclr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sclr.setText("Clear");
        sclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sclrActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("<-Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("BHK");

        isbhk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbhkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(isbhk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vsloc)
                            .addComponent(vsprice)
                            .addComponent(vsqft))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isloc)
                            .addComponent(isprice)
                            .addComponent(isqft, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vsfur)
                            .addComponent(vspar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yespar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesfur, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nospar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nofur, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vsaddr)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(displayselltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ssub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sclr))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(225, 225, 225))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsloc))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isprice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsprice))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vsqft)
                    .addComponent(isqft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isbhk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vsfur)
                    .addComponent(yesfur)
                    .addComponent(nofur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vspar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nospar)
                        .addComponent(yespar)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsaddr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssub)
                    .addComponent(sclr))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayselltxt)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void islocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_islocActionPerformed

    private void isqftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isqftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isqftActionPerformed

    private void ispriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ispriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ispriceActionPerformed

    private void yesparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesparActionPerformed

    private void sclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sclrActionPerformed
        // TODO add your handling code here:
        isloc.setText("");
        isprice.setText("");
        isqft.setText("");
        isaddr.setText("");
        isbhk.setText("");
        if(yesfur.isSelected())
        {
            yesfur.setSelected(false);
        }
        else{
             nofur.setSelected(false);
        }
        //String par;
        if(yespar.isSelected())
        {
            yespar.setSelected(false);
        }
        else{
            nospar.setSelected(false);
        }
    }//GEN-LAST:event_sclrActionPerformed

    private void ssubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssubActionPerformed
        // TODO add your handling code here:
        //System.out.println(LoginF.em);
        String loc = isloc.getText();
        String price = isprice.getText();
        String sqft = isqft.getText();
        String addr = isaddr.getText();
        String bhk = isbhk.getText();
        String fur = "";
        
        if(yesfur.isSelected())
        {
            fur = "Yes";
        }
        else{
            fur="No";
        }
        String par;
        if(yespar.isSelected())
        {
            par = "Yes";
        }
        else{
            par="No";
        }
        
        
        if(loc.length()!=0 && price.length()!=0 && sqft.length()!=0 && addr.length()!=0 && fur.length()!=0 && par.length()!=0){
            displayselltxt.setText("Submitted succesfully");
            try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/realestate","root","yashaswini22")){
                String sql="insert into seller values(\""+LoginF.em+"\",\""+loc+"\","+price+","+sqft+","+bhk+",\""+fur+"\",\""+par+"\",\""+addr+"\")";
                PreparedStatement pstmt=conn.prepareStatement(sql);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"insertion successfull");
                conn.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            } 
        }
        
    }//GEN-LAST:event_ssubActionPerformed

    private void yesfurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesfurActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_yesfurActionPerformed

    private void nofurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nofurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nofurActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MainPage b1 = new MainPage();
        b1.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void isbhkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbhkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbhkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellerform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellerform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel displayselltxt;
    private javax.swing.JTextArea isaddr;
    private javax.swing.JTextField isbhk;
    private javax.swing.JTextField isloc;
    private javax.swing.JTextField isprice;
    private javax.swing.JTextField isqft;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton nofur;
    private javax.swing.JRadioButton nospar;
    private javax.swing.JButton sclr;
    private javax.swing.JButton ssub;
    private javax.swing.JLabel vsaddr;
    private javax.swing.JLabel vsfur;
    private javax.swing.JLabel vsloc;
    private javax.swing.JLabel vspar;
    private javax.swing.JLabel vsprice;
    private javax.swing.JLabel vsqft;
    private javax.swing.JRadioButton yesfur;
    private javax.swing.JRadioButton yespar;
    // End of variables declaration//GEN-END:variables
}
